### PR TITLE
Better NPE messages in CollectionUtils with Objects.requireNonNull

### PR DESCRIPTION
**Pull request by dota17**
for [COLLECTIONS-604](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-604?filter=allopenissues) & [COLLECTIONS-600](https://issues.apache.org/jira/projects/COLLECTIONS/issues/COLLECTIONS-600?filter=allopenissues)

### CODE REVIEW

**Comment by garydgregory** [comment]
I'm OK with normalizing our internals on `Objects.requireNonNull` but I really do not like using full sentences for parameter validation.

IOW, say:
```
Objects.requireNonNull(foo, "foo");
```
Do NOT say:
```
Objects.requireNonNull(foo, "The first collection must not be null.");
Objects.requireNonNull(foo, "foo must not be null.");

```

**Comment by michael-o** [comment]
I agree here with @garydgregory . I the message should solely consist of the arg/var name.

**Comment by dota17** [comment]
Thanks @garydgregory @michael-o . I had keep it simple now.
@garydgregory @michael-o What about the issue returned IllegalArgumentException and now would return NullPointerException?  
Thanks @kinow .

**Comment by garydgregory** [comment]
> Thanks @garydgregory @michael-o . I had keep it simple now.
> @garydgregory @michael-o What about the issue returned IllegalArgumentException and now would return NullPointerException?
> Thanks @kinow .

@dota17 
The PR looks good. I think it is OK in this case to trade one unchecked exception for another. NPE is more precise and does not break binary compatibility of method signatures.

**Comment by michael-o** [comment]
> 
> 
> > Thanks @garydgregory @michael-o . I had keep it simple now.
> > @garydgregory @michael-o What about the issue returned IllegalArgumentException and now would return NullPointerException?
> > Thanks @kinow .
> 
> @dota17
> The PR looks good. I think it is OK in this case to trade one unchecked exception for another. NPE is more precise and does not break binary compatibility of method signatures.

Correct, especially there unchecked should be swapped for correctness. IAE and NPE almost always indicate programming errors.

**Pull request merged**
