### PR TITLE
Simplify method CollectionUtils#isEqualCollection

### PR DESCRIPTION
**Pull request by StudentGu**
Simplify method CollectionUtils#isEqualCollection

### CODE REVIEW

**Comment by garydgregory** [comment]
@StudentGu 

Thank you for your PR.

I removed some duplication in `CardinalityHelper and the class now reuses the existing `HashBag` class, see `org.apache.commons.collections4.CollectionUtils.CardinalityHelper.equals(Collection<?>, Collection<?>)`:
https://github.com/apache/commons-collections/blob/3f7cb39b6d1828c02ba93c0622ae4fef1f29dda0/src/main/java/org/apache/commons/collections4/CollectionUtils.java#L66-L68

This PR can be closed IMO.

**Comment by StudentGu** [comment]
> @StudentGu
> 
> Thank you for your PR.
> 
> I removed some duplication in `CardinalityHelper and the class now reuses the existing `HashBag`class, see`org.apache.commons.collections4.CollectionUtils.CardinalityHelper.equals(Collection, Collection)`:
> 
> https://github.com/apache/commons-collections/blob/3f7cb39b6d1828c02ba93c0622ae4fef1f29dda0/src/main/java/org/apache/commons/collections4/CollectionUtils.java#L66-L68
> 
> This PR can be closed IMO.

@garydgregory 

Oh, My brother, I want contribute to the project.

**Comment by garydgregory** [comment]
Hello @StudentGu 

If you are looking for contribution inspiration, please see https://issues.apache.org/jira/projects/COLLECTIONS

Closing: Information provided.

**Comment by StudentGu** [comment]
Thanks! @garydgregory 
t is a great pity that I don't have an jira account now. 
I have applied to the community for an jira account through `https://selfserve.apache.org/jira-account.html`  and select the commons-collections, but there has been no reply.
Could you help me deal with it?

**Comment by garydgregory** [comment]
@StudentGu 
All you have to do to get a Jira account is apply. The application form exists to avoid bots from creating tickets and spam which was a problem in the past.

**Pull request closed without merging**
