### PR TITLE
Added unit tests to increase code coverage

### PR DESCRIPTION
**Pull request by vamsi-kavuri**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks!

**Comment by PascalSchumacher** [comment]
`assertEquals(MapUtils.getDouble(in,"key", 0.0), 2.0, 0);` etc. should be `assertEquals(2.0, MapUtils.getDouble(in,"key", 0.0), 0);` because it is `assertEquals(double expected, double actual, double delta)`

Also two test fail for locales that do no use `.` as the decimal separator (e.g. germany)

```
Failed tests:
  MapUtilsTest.testgetDoubleValue:956 expected:<20.0> but was:<2.0>
  MapUtilsTest.testgetFloatValue:974 expected:<20.0> but was:<2.0>
```

**Comment by vamsi-kavuri** [comment]
@PascalSchumacher Thanks for the feedback. I haven't thought of german locale. good catch. I will update it in a different PR.

**Comment by PascalSchumacher** [comment]
Thanks! Looking forward to the pull request!

**Comment by vamsi-kavuri** [comment]
@PascalSchumacher I am late by an hour. Decimal separators are added by gregory
https://github.com/apache/commons-collections/commit/641aa1c663ebead0189bf001a06ee56463070ddb

**Comment by PascalSchumacher** [comment]
Sorry about that. :(

But the correct parameter order part of you pull request is still relevant. It would be nice if you could create a new rebased pull request for that. Thanks!

**Pull request closed without merging**
