### PR TITLE
Adding Power support

### PR DESCRIPTION
**Pull request by lysannef**
Adding support for travis job on ppc64le architecture.

### CODE REVIEW

**Comment by lysannef** [comment]
Ppc64le job is passing. Can this be merged?

**Comment by lysannef** [comment]
HI @garydgregory, 
could you please help me with this, every time I edit any other part of the file, it changes the EOL.
Is there some way of setting it.

**Comment by michael-o** [comment]
Use this on Windows:

```
core.autocrlf=true
core.eol=native
core.safecrlf=true
```

**Comment by lysannef** [comment]
@garydgregory  Fixed issues with EOL

**Pull request merged**
