### PR TITLE
[COLLECTIONS-774] - Bump version maven-antrun-plugin 3.0.0

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Looks good to me, but a jump from 1.8 to 3.0.0 probably needs either some testing or someone that knows how antrun plugin is used and can confirm the update won't break anything.

**Comment by kinow** [comment]
p.s. @arturobernalg good to see you around here again! :wave: I thought it was one of the PR's generated by dependabot :smile:

**Comment by arturobernalg** [comment]
Hi @kinow 

i'm glad to contribute.

**Comment by garydgregory** [comment]
Duplicates #170

**Pull request closed without merging**
