### PR TITLE
[COLLECTIONS-607] BidirectionalHashMap

### PR DESCRIPTION
**Pull request by dota17**

### CODE REVIEW

**Comment by garydgregory** [comment]
Hi @dota17 
How is this different from the current implementations of `org.apache.commons.collections4.BidiMap`?

**Comment by dota17** [comment]
> current implementations of

Adding a hash table based BidiMap.

**Comment by dota17** [comment]
If the feature is not necessary, I will close it.

**Comment by garydgregory** [comment]
> > current implementations of
> 
> Adding a hash table based BidiMap.

@dota17 
You did not really answer my question :-(
Do you mean that this PR is the same as `org.apache.commons.collections4.bidimap.DualHashBidiMap<K, V>` ?

**Pull request closed without merging**
