### PR TITLE
travis: add java 10 to build

### PR DESCRIPTION
**Pull request by grimreaper**

### CODE REVIEW

**Comment by kinow** [comment]
The change looks OK @grimreaper , though in commons-io, for some reason [we are using openjdk10](https://github.com/apache/commons-io/blob/30f81c47f7ea0e9f743e08e73f48c0cfcfb746ff/.travis.yml#L19), and skipping oracle jdk 10.

And it failed due to clirr tests. Maybe if you rebase your changes it will work this time?

Cheers
Bruno

**Comment by grimreaper** [comment]
> for some reason [we are using openjdk10](https://github.com/apache/commons-io/blob/30f81c47f7ea0e9f743e08e73f48c0cfcfb746ff/.travis.yml#L19), and skipping oracle jdk 10.

This is for legal reasons. Oracle is making is difficult to use their JDKs. When I rebase I'll switch this to openjdk too.

**Comment by michael-o** [comment]
I see absolutely no reason to test against Java 9 or 10. It is either <= 8 or >= 11.

**Comment by garydgregory** [comment]
I agree with @michael-o : At work, we are on Java 8 and 11; and some Java 7 on maintenance branches. Java 9 and 10 are not in the picture..

**Comment by grimreaper** [comment]
Alright. I'll make a new PR with OpenJDK 11.

**Pull request closed without merging**
