### PR TITLE
Fix punctuation and minor JavaDoc issues

### PR DESCRIPTION
**Pull request by mawiesne**
- fixes misplaced symbols in JavaDoc (mainly in Hasher, CountingLongPredicate)
- resolves grammar and punctuation issues

### CODE REVIEW

**Comment by mawiesne** [comment]
Ping @garydgregory @kinow

**Review by garydgregory — CHANGES_REQUESTED** [review]
@mawiesne 
Thank you for your PR.
I am worried that this will clash with ongoing work in PRs in the bloom filter package.
Would you please update the PR to not touch that package?

**Review by kinow — APPROVED** [review]
Thank you @mawiesne !

**Comment by mawiesne** [comment]
> Would you please update the PR to not touch that package?

I did - changes in bloomfilter package reverted.

**Pull request merged**
