### PR TITLE
[COLLECTIONS-759]: add newline at end of file, and convert to unix (LF instead of CRLF) fixing checkstyle

### PR DESCRIPTION
**Pull request by kinow**
As per title, fixing the Travis CI build that is broken at the moment due to checkstyle issues. There are some files that were missing newline at end of file (git).

Added the extra line, but after running `mvn` got the error again. Then noticed it was a CRLF vs. LF issue. Ran the files through `dos2unix`, and finally `mvn` command (default build target, same as in Travis) passed.

Now :crossed_fingers: and wait to see what Travis reports.

Bruno

### CODE REVIEW

**Comment by michael-o** [comment]
I'd be better to have .gitattributes to handle such cases...

**Comment by kinow** [comment]
> I'd be better to have .gitattributes to handle such cases...

Hi @michael-o good point, [lang] already has one. I never added one to an existing project. I tried dropping the current commit, and adding the `.gitattributes` from [lang], but running `mvn` checkstyle complained again about CRLF. Are the changes applied only after cloning the repository?

**Comment by dota17** [comment]
@kinow Now this branch has confilcts in the following files : src/changes/changes.xml .
@garydgregory It's fine for CI.  Can you review and merge it after the confilcts is resolved.

**Comment by dota17** [comment]
@kinow There is an unused import which maybe remove.

[ERROR] src/test/java/org/apache/commons/collections4/CollectionUtilsTest.java:[22,15] (imports) UnusedImports: Unused import - org.junit.Assert.assertNotSame.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:31 min
[INFO] Finished at: 2020-04-21T09:49:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:check (default-cli) on project commons-collections4: You have 1 Checkstyle violation. -> [Help 1]

**Comment by kinow** [comment]
Thanks @dota17 ! Updating it now... (after I test with `mvn` this time).

**Pull request merged**
