### PR TITLE
COLLECTIONS-701 SetUniqueList.add() crashes due to infinite recursion…

### PR DESCRIPTION
**Pull request by drajakumar**
… when it receives itself

### CODE REVIEW

**Comment by garydgregory** [comment]
Hi @drajakumar ,

I'm not sure this patch makes sense. Take a look at ```org.apache.commons.collections4.list.Collections701Test```: For ```ArrayList``` and ```HashSet```, adding a collection to itself is fine. 

In this patch, the argument is not only silently ignored, but the behavior is not even documented. Whatever we do, we really need to document _anything_ that deviates from the standard JRE ```List``` contract.

IMO, the fix should be so that a ```SetUniqueList``` behaves like a ```ArrayList``` and ```HashSet```, it just works.

**Comment by garydgregory** [comment]
You did not have to close the PR, I was hoping you would provide a more complete solution ;-)

**Comment by drajakumar** [comment]
@garydgregory can you kindly check the new fix, thank you!

**Comment by drajakumar** [comment]
@garydgregory can you kindly check the new fix, thank you!

**Pull request closed without merging**
