### PR TITLE
COLLECTIONS-785 - Add constant variable

### PR DESCRIPTION
**Pull request by arturobernalg**
The idea it's reuse the constant variable in all the applications.

- `"["`
- "]"
- ":"
- ","

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Looks good to me. Following the pattern of the exiting `CollectionUtils.INDEX_NOT_FOUND`. :+1:

**Comment by arturobernalg** [comment]
> Looks good to me. Following the pattern of the exiting `CollectionUtils.INDEX_NOT_FOUND`. 👍

Thank you @kinow

**Comment by arturobernalg** [comment]
Hi @kinow 

should i change something?

**Comment by kinow** [comment]
> Hi @kinow
> 
> should i change something?

Hi @arturobernalg sorry, I left it open to give time to others to review it, but also because I was going to create a JIRA. Even though it's a small change, I think it's OK to document it in the changelog (and add a thanks for your contribution there :-)

Could you create the JIRA? I'll take care of the rest and merge it :+1: 

Bruno

**Comment by arturobernalg** [comment]
Hi @kinow 

Jira created COLLECTIONS-785

**Comment by kinow** [comment]
That was quick! I couldn't even finish my coffee :coffee: . Thanks @arturobernalg , let me update the JIRA/changes.xml and merge it.

**Comment by arturobernalg** [comment]
> That was quick! I couldn't even finish my coffee ☕ . Thanks @arturobernalg , let me update the JIRA/changes.xml and merge it.

hahaha , take your time,

TY

**Review by kinow — APPROVED** [review]

**Comment by kinow** [comment]
Added changes.xml entry, updated JIRA fixVersion/releaseVersion and resolved it. Thanks @arturobernalg ! :+1:

**Pull request closed without merging**
