### PR TITLE
Replace explicit type with <>.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
Change looks good, and CI error appears to be some fragile test but not sure. Thanks @arturobernalg :+1:

**Comment by arturobernalg** [comment]
> Change looks good, and CI error appears to be some fragile test but not sure. Thanks @arturobernalg 👍

No clue what is happening here.

**Review by Simulant87 — APPROVED** [review]
Looks good to me

**Review by kinow — APPROVED** [review]
Change looks good, CI is happy. Thanks @arturobernalg !

**Pull request merged**
