### PR TITLE
Replace Clirr with japicmp, since clirr does not handle Java 8 defaul…

### PR DESCRIPTION
**Pull request by britter**
…t methods

### CODE REVIEW

**Comment by britter** [comment]
The build produces:

```
[INFO] --- japicmp-maven-plugin:0.12.0:cmp (default-cli) @ commons-collections4 ---
[INFO] Skipping execution because parameter 'skip' was set to true.
```

And I don't understand why. When calling `mvn site`, the japicmp report is created. But the check goal is always skipped...

**Comment by chtompki** [comment]
Yeah I did that. If the artifact is a pom only module, japicmp kinda blows up and falls over. So we have to un-skip it down here in the projects.

**Comment by chtompki** [comment]
@britter - try japicmp version 0.13....

**Comment by CasualSuperman** [comment]
> Yeah I did that. If the artifact is a pom only module, japicmp kinda blows up and falls over. So we have to un-skip it down here in the projects.

That sounds like a use case for the [packagingSupported](https://siom79.github.io/japicmp/MavenPlugin.html) configuration option. It even says:
>Helpful if you define the plugin in a root pom.

**Pull request closed without merging**
