### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by marcwrobel**
Fix various minor typos in :

- project documentations,
- javadoc and comments,
- method attribute and variable names,
- test method names.

### CODE REVIEW

**Comment by garydgregory** [comment]
Holding off on this one until #320 is merged.

**Comment by marcwrobel** [comment]
@garydgregory, I just resolved the conflicts. #320 has been merged so this PR is ready for review.

**Comment by marcwrobel** [comment]
@garydgregory, conflicts resolved.

**Comment by marcwrobel** [comment]
@garydgregory ?

**Comment by garydgregory** [comment]
> @garydgregory ?

100+ files changed puts this on the todo list for the weekend most likely...

**Comment by marcwrobel** [comment]
@garydgregory, will it help you if I split this PR into multiple smaller PRs ?

**Comment by garydgregory** [comment]
That might be worse, it's just the same to review but spread out ;-)

**Comment by marcwrobel** [comment]
I resolved a conflict and rolled back the changes in files that were also changed in #335 (only two typos were rolled back). The two PRs should not conflict with each other.

**Comment by garydgregory** [comment]
Hi @marcwrobel 
Please revert changes to the `bloomfilter` package, I don't make to make work for #335 
TY

**Comment by marcwrobel** [comment]
@garydgregory, all changes related to the bloomfilter package have been reverted.

**Review by garydgregory — APPROVED** [review]
LGTM

**Pull request merged**
