### PR TITLE
Updated the fail() exceptions with Junit5.

### PR DESCRIPTION
**Pull request by dota17**

### CODE REVIEW

**Comment by garydgregory** [comment]
@dota17 The title says "WIP". Are you still working on it?

**Comment by dota17** [comment]
> @dota17 The title says "WIP". Are you still working on it?

Yes, I am. 
If anyone has time to review, it would be really nice. ;-)

Thanks

**Comment by garydgregory** [comment]
> > @dota17 The title says "WIP". Are you still working on it?
> 
> Yes, I am.
> If anyone has time to review, it would be really nice. ;-)
> 
> Thanks

Hi @dota17 
This PR currently touches **124** files, which is a lot to review. Personally, for me to review this, I'd want to know the PR is as best as you can make it, because, as you can imagine, I really do not want to do it twice! ;-) So either it's WIP or it is as good as it is going to get from your POV at least. Please let us know...

**Comment by dota17** [comment]
Hi @garydgregory 
Under the folder
commons-collections/src/test/java/org/apache/commons/collections4 (junit5WithExceptions),
I executed the command to get the fails without annotate and import.
  `grep -R fail * |  grep -v import |grep -v "\/\/" | grep -v "*"`
The last 58 lines only use the fail without exception to get the failure details.
I had used JUnit 5's assertThrows() in the tests instead of fail() or Assert.fail() in the 
132 files.

**Comment by dota17** [comment]
Hi @garydgregory 
I want to migrate to JUnit5 Jupiter. Such as the pr :
https://github.com/apache/commons-csv/pull/49
Is it OK ?

**Comment by dota17** [comment]
comparators/AbstractComparatorTest.java
comparators/BooleanComparatorTest.java
comparators/ComparatorChainTest.java
comparators/FixedOrderComparatorTest.java
comparators/ReverseComparatorTest.java
iterators/BoundedIteratorTest.java
iterators/PeekingIteratorTest.java
iterators/PushbackIteratorTest.java
iterators/SkippingIteratorTest.java
keyvalue/AbstractMapEntryTest.java
keyvalue/DefaultKeyValueTest.java
keyvalue/DefaultMapEntryTest.java
keyvalue/TiedMapEntryTest.java
keyvalue/UnmodifiableMapEntryTest.java
map/LazyMapTest.java
map/LazySortedMapTest.java
properties/AbstractPropertiesFactoryTest.java
properties/PropertiesFactoryTest.java
properties/SortedPropertiesFactoryTest.java

org.junit.jupiter.api.Test was used as a drop in replacement for org.juit.Test without arguments. These Tests are with arguments, how to proceed?

**Review by kinow — COMMENTED** [review]
@dota17 conflicts in this PR :+1:

**Comment by garydgregory** [comment]
I just merged a series of JUnit 5 PRs; if this PR still contains changes not covered in git master, please rebase, if not, please close it. TY!

**Comment by garydgregory** [comment]
I think JUnit 5 work might be done in master?

**Comment by garydgregory** [comment]
Hello @dota17 

The migration to JUnit 5 is complete in git master. Please create a new PR is if find something amiss.

**Pull request closed without merging**
