### PR TITLE
Remove duplicate condition in FixedOrderComparator equals()

### PR DESCRIPTION
**Pull request by saurabh-rahate**
This PR is to remove one duplicate condition in `FixedOrderComparator- equals()` and simplifying the conditions.

### CODE REVIEW

**Review by Claudenw — APPROVED** [review]
LGTM.  Added more tests and removed unnecessary conditions.

**Comment by garydgregory** [comment]
Hello @saurabh-rahate 
Thank you for your PR. Would you please resolve conflicts and rebase on master?

**Comment by saurabh-rahate** [comment]
> Hello @saurabh-rahate Thank you for your PR. Would you please resolve conflicts and rebase on master?

@garydgregory I resolved conflicts and rebased.

**Comment by garydgregory** [comment]
@saurabh-rahate 

- Thank you for your PR, see my notes for future contributions.
- This was done differently in git master.
- You are credited in `changes.xml`.
- Closing this PR.

**Pull request closed without merging**
